language:node_js
node_js:
  - "0.10.25"
sudo:required
before install:
  - sudo apt-get update -qq
  - sudo apt-get install npm
  - sudo npm install -g node-gyp
  - npm install
  - sudo npm install dalek-cli -g
  - npm install dalekjs --save-dev
